google_api_key = "AIzaSyDvgNwTKErMBsGENrIoa7cIAuqBYX1zbQQ"

[postgres]
host = "ep-winter-fog-a8u0htz2-pooler.eastus2.azure.neon.tech"
port = "5432"
dbname = "neondb"
user = "neondb_owner"
password = "npg_LZm8P3vBorEN"